### ISSUE TITLE
Program won't run on ubuntu for me

### ISSUE THREAD

**Issue by Hypnotoad90** [willm/DDEXUI#20]
Hi there, I just found this as it would possibly be quite useful for me. However I'm having trouble getting it to run in Ubuntu:

If I try: python metadata_form.py

I get the error: 

Traceback (most recent call last):
  File "metadata_form.py", line 2, in <module>
    import tkinter.ttk as tk
ImportError: No module named tkinter.ttk

If I try: python3.4 metadata_form.py

I get the error:

Traceback (most recent call last):
  File "metadata_form.py", line 4, in <module>
    from DDEXUI.ddex.ddex_builder import DDEXBuilder
ImportError: No module named 'DDEXUI'

Please advise, I did install the dependencies using pip install -r requirements.txt as instructed.

Thanks.

**Comment by willm** [comment]
I'm away this week-end, with no access to a computer,  I will look into it when I'm back on monday evening.

**Comment by willm** [comment]
Something off the top of my head to try is to make sure you've cloned the ddexui project to somewhere in your pythonpath. Or adding where you cloned it to your python path.

**Comment by Hypnotoad90** [comment]
I'm having trouble amending my python path (sys.path.appened() doesn't seem to save), but there's no rush. I'm wondering in general are you able to provide example XML files that are generated? My ultimate aim here is to better understand the DDEX schema and the more common labels used and their hierarchies etc..., there unfortunately seems to be few if any examples of a simple DDEX ERN XML file for a single track for instance.

As such I'm not really familiar with python at all, I was just hoping to use this program to tinker around and produce my own XML files to better understand the standard.

Thanks again.

**Comment by willm** [comment]
Sure,  here's an example XML https://github.com/willm/DDEXUI/blob/master/ddex/tests/resources/ddex-sample.xml

**Comment by willm** [comment]
Hi, Are you sure you are running the program with python 3 and not python 2? The default ubuntu python install is 2.

from the root of the project, try running:

```
sudo apt-get install python3-pip python3-tk libxslt1-dev libxml2-dev libjpeg-dev tk8.6-dev tcl8.6-dev
pip3 install -I -r requirements.txt
PYTHONPATH=$(readlink -f ..):$PYTHONPATH python3 metadata_form.py
```

I apologise if this seems obscure, I haven't worked on this project for a while.

**Comment by Hypnotoad90** [comment]
No worries. I've run those exact commands. 

On doing: PYTHONPATH=$(readlink -f ..):$PYTHONPATH python3 metadata_form.py

I still get the error: 

Traceback (most recent call last):
  File "metadata_form.py", line 4, in <module>
    from DDEXUI.ddex.ddex_builder import DDEXBuilder
ImportError: No module named 'DDEXUI'

I should note that on running the 2nd requirements.txt command, towards the end I got these errors:

error: could not delete '/usr/local/lib/python3.4/dist-packages/mutagenx/easyid3.py': Permission denied

---

Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;**file**='/tmp/pip_build_andross/mutagenx/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-r5esh0vv-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_andross/mutagenx
Storing debug log for failure in /home/andross/.pip/pip.log

**Comment by willm** [comment]
Hmm that's strange, are you running that command from the root directory of the project?
