### ISSUE TITLE
Not working with MacOs

### ISSUE THREAD

**Issue by ghost** [willm/DDEXUI#21]
Hi,
I've been trying to make it work on mac with Python Launcher & Idle nothing working can you help me?

This is an awesome project.

Thank you

**Comment by willm** [comment]
Hi, could you give a bit more detail than nothing working? If you're trying to run the UI, I've kind of abandoned it. I suggest you use it as a library instead.

**Comment by ghost** [comment]
try to start the program as u said in Terminal and Idle event with Python Launcher on mac but nothing happen. how to use it as a library then? I'm new to python and DDEX

**Comment by willm** [comment]
Ah OK, let me try to build it on a mac and I'll get back to you with some instructions.

**Comment by willm** [comment]
can you try running this branch https://github.com/willm/DDEXUI/tree/run-on-osx ?

**Comment by ghost** [comment]
Ok I tried in Terminal, and i got this : 
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.chdir('/Users/ordericayatsou/Downloads/DDEXUI-run-on-osx')
>>> os.getcwd()
'/Users/ordericayatsou/Downloads/DDEXUI-run-on-osx'
>>> python metadata_form.py
  File "<stdin>", line 1
    python metadata_form.py
                       ^
SyntaxError: invalid syntax
>>>

**Comment by ghost** [comment]
On python 3.6.1 shell i got this : 
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>> WARNING: The version of Tcl/Tk (8.5.9) in use may be unstable.
Visit http://www.python.org/download/mac/tcltk/ for current information.
os.getcwd()
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    os.getcwd()
NameError: name 'os' is not defined
>>> import os
>>> os.chdir('/Users/ordericayatsou/Downloads/DDEXUI-run-on-osx')
>>> python metadata_form.py
SyntaxError: invalid syntax
>>>

**Comment by willm** [comment]
Install python3 http://docs.python-guide.org/en/latest/starting/install3/osx/
run: 
```
pip3 install -r requirements.txt
python3 metadata_form.py
```

**Comment by willm** [comment]
Just so you know, this project isn't really finished. It needs a bit of work to get it working. The code lets you write ddex files in python, but the user interface isn't really ready for use. Unless you're willing to spend some time helping with it, it might be worth looking at another option. Sorry, I know that's not very helpful.

**Comment by ghost** [comment]
Ok,
It's working now thanks a lot. Sure i can help if you need

**Comment by willm** [comment]
Hey, Just to let you know, I've decided to have a go at writing a better front end for this library, I'm going to drop tkinter and try and use CEF Python instead. I'll update when I have something worth trying.

**Comment by ghost** [comment]
Nice move!

**Comment by ivanwoodson** [comment]
Any updates on this for Max OSX?

**Comment by ivanwoodson** [comment]
Any updates on this for MacOs. I would love to help.
